# This is a basic workflow to help you get started with Actions

name: Build and Test Java Spring Boot Application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

  # Allows you to run this workflow manually from the Actions tab
 # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SNS_TOPIC_ARN: ${{ secrets.AWS_SNS_TOPIC_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK 8 # set up java 8
        uses: actions/setup-java@3
        with:
          java-version: '8'
      - name: build with Maven
        run: mvn clean install
      - name: Run tests
        run: mvn test
       
     
      
        
   
